version: 1.0
name: phone

workflows:
  flutter-build:
    name: Flutter Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install Android SDK command-line tools
        script: |
          # Install command-line tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d /sdk/cmdline-tools
          mkdir -p /sdk/cmdline-tools/bin
          mv /sdk/cmdline-tools/cmdline-tools/* /sdk/cmdline-tools/bin
          /sdk/cmdline-tools/bin/sdkmanager --install "cmdline-tools;latest"
      - name: Accept Android SDK licenses
        script: |
          yes | flutter doctor --android-licenses
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --split-per-abi --no-tree-shake-icons
      - name: Build IPA
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/app/outputs/flutter-apk/app-*.apk
      - build/ios/iphoneos/Runner.app
      - build/ios/ipa/Runner.ipa
